### ISSUE TITLE
more then one motion entity?

### ISSUE THREAD

**Issue by fisch55** [OliverHi/blueprints#1]
Hi, is it possible toi add one more motion sensor.... like or

if motion 1 or motion 2 than...

**Comment by Tanjohnson99** [comment]
Would like to know how to do with more than 1 sensor. 
Thanks

**Comment by OliverHi** [comment]
Since 2022.4 of Home Assistant this is possible. I added it now in https://github.com/OliverHi/blueprints/commit/7269effa987a996b2614966ae06783952385cbf0
